server:
  port: 8890
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.176.44/data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: VHQBfXls70EIYxS3*

